0glabs/0g-da-client

- disperser/batcher/batcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/34)
> Stop process blob, if maximum times is reached

- disperser/batcher/transactor/transactor.go
- disperser/cmd/batcher/flags/flags.go
- disperser/contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/35)
> Estimate gas for submitVerifiedCommitRoots by default

- disperser/batcher/batcher.go
- disperser/batcher/confirmer.go
- disperser/batcher/finalizer.go
- disperser/batcher/slice_signer.go
- disperser/cmd/batcher/main.go
- disperser/cmd/combined_server/main.go
- disperser/disperser.go
- disperser/store.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/36)
> Use the metadata from the first blob for any duplicate blobs

- disperser/batcher/batcher.go
- disperser/signer/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/37)
> Remove prefix for signer address

- disperser/batcher/slice_signer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/38)
> Update signed slice threshold

- disperser/apiserver/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/43)
> Add tiny rate limiter for disperser

- disperser/apiserver/server.go
- disperser/batcher/slice_signer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/44)
> Fix log format

- disperser/batcher/batcher.go
- disperser/batcher/slice_signer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/45)
> Optimize error handling

- .gitignore
- Dockerfile
- run/run.sh
- run/start.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/46)
> Add Dockerfile

- .gitignore
- README.md
- run/README.md
- run/run.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/47)
> Update docker config

- common/ratelimit/limiter_cli.go
- disperser/apiserver/server.go
- disperser/cmd/apiserver/main.go
- disperser/cmd/combined_server/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/48)
> refactor ratelimit

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/50)
> Add link to DA retriever

- Dockerfile
- run/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/51)
> fix docker for ssl

- README.md
- run/run.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/53)
> update timeout in readme

- disperser/apiserver/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/54)
> modify error messgae

- .dockerignore
- combined.Dockerfile
- run/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/55)
> Add the Dockerfile for client from the build

- disperser/batcher/slice_signer.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/57)
> Check aggregated key and signature

- disperser/apiserver/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/56)
> Add check for StorageRoot in RetrieveBlob

- combined.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/58)
> fix docker build warning

- api/proto/disperser/disperser.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/60)
> Fix BlobHeader order

- disperser/apiserver/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/61)
> Update the maximum acceptable block size

- disperser/batcher/transactor/transactor.go
- disperser/contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/63)
> estimate gas for SubmitOriginalData

- disperser/batcher/finalizer.go
- disperser/batcher/transactor/transactor.go
- disperser/cmd/batcher/main.go
- disperser/cmd/combined_server/main.go
- disperser/contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/65)
> add logger in contract

- disperser/batcher/slice_signer.go
- disperser/signer/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/66)
> give informal address a try

- disperser/contract/contract.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/68)
> increase gas price

- README.md
This pull request includes updates to the `README.md` file to correct and update various documentation links.
Documentation updates:
* Updated the link for the 0G DA spec to point to the correct deep dive documentation.
* Updated the links for Testnet Configuration and Contract Addresses to point to the current locations in the documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/0glabs/0g-da-client/69)
> replaced the broken links
